apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-persistent-claim
  namespace: rupchand
spec:
  volumeMode: Filesystem
  storageClassName: volume-rupchand
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi