apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-volume
  namespace: rupchand
  labels:
    type: local
spec:
  storageClassName: mysql-rupchand
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: rupchand
  name: mysql-volume-claim
spec:
  storageClassName: mysql-rupchand
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi